#spring.application.name=produits-services


spring:
  application:
    name: produits-services
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/produitdb?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:1305/eureka/

# Keycloak
keycloak:
  realm: spring
  baseUrl: http://localhost:8087
  username: admin
  password: 221Jamono2.0
  grant-type: password
  tokenUrl: http://localhost:8087/realms/spring/protocol/openid-connect/token
  introspection-uri: http://localhost:8087/realms/spring/protocol/openid-connect/token/introspect
  client-secret: ir3qrDh9I5kKLU3qJaC4LfKkhL2at0Ec
  client-id: gaydelID
  logout-url: http://localhost:8087/realms/spring/protocol/openid-connect/logout

# jwt
jwt:
  jwk-set-uri: http://localhost:8087/realms/spring/protocol/openid-connect/certs
  token:
    converter:
      principal-attribute: preferred_username




server:
  port: 1414